"""empty message

Revision ID: 1e1d49589a53
Revises: 
Create Date: 2018-07-31 13:43:47.191452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1d49589a53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uname', sa.String(length=16), nullable=True),
    sa.Column('upassword', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
